# Use the official Swift image.
FROM swift:5.5

# Set the working directory.
WORKDIR /app

# Copy the current directory contents into the container at /app.
COPY . /app

# Define the command to run your application.
ENTRYPOINT ["swift", "code.swift"]
