import React, { useState } from 'react';
import SignUp from './signup';
import Link from 'next/link';
import '../app/globals.css';


const MainPage = () => {

  {/* Generated by ChatGPT */}  
  const [showSignUp, setShowSignUp] = useState(false);

  const handleSignUp = () => {
    setShowSignUp(!showSignUp);
  }


  return (
    <div className="flex h-screen">
      
      <div className="w-1/4 bg-gray-800 text-white p-5 mt-40 h-screen fixed">
        <h2 className="text-2xl font-semibold mb-6">Categories</h2>
        <ul className="list-none">
          <li className="mb-4 hover:bg-gray-600 p-2 rounded cursor-pointer">Templates</li>
          <li className="mb-4 hover:bg-gray-600 p-2 rounded cursor-pointer">
            <Link href="/blog-posts">Blog Posts</Link>
          </li>
        </ul>
      </div>

      {/* Generated by ChatGPT */}
      <div className="flex-1 bg-gray-100 p-6">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-5xl font-bold text-gray-800">Scriptorium</h1>
          <div className="space-x-4">

            <Link href="/login">
                <button className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">Log In</button>
            </Link>

            <Link href="/signup">
                <button 
                    className="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600"
                    onClick={handleSignUp}
                >
                    Sign Up
                </button>
            </Link>
          </div>
        </div>

        {showSignUp && <SignUp />}

       
      </div>
    </div>
  );
};

export default MainPage;

