import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import Link from 'next/link';
import '../app/globals.css';

const LoggedIn = () => {
 const router = useRouter();
 const [avatar, setAvatar] = useState(null);
 const [isAdmin, setIsAdmin] = useState(false);
  
 useEffect(() => {
    const token = localStorage.getItem('accessToken');
    if (token) {
      const user = JSON.parse(atob(token.split('.')[1])); // Logic influenced by ChatGPT
      setIsAdmin(user.role === 'ADMIN');  // Logic influenced by ChatGPT
    }
  }, []);

 {/* Generated by ChatGPT */}
 useEffect(() => {
  const fetchAvatar = async () => {
    try {
      const accessToken = localStorage.getItem('accessToken');

      const response = await fetch('http://localhost:3000/api/users/retrieve', {
        headers: {
          Authorization: `Bearer ${accessToken}`,
        },
      });

      if (response.ok) {
        const userData = await response.json();
        setAvatar(userData.avatar);
      } else {
        console.error('Failed to fetch user data');
      }
    } catch (error) {
      console.error('Error fetching user data:', error);
    }
  };

  fetchAvatar();
}, []);


 {/* Generated by ChatGPT */}
 const handleLogout = () => {
    localStorage.removeItem('accessToken');
    localStorage.removeItem('refreshToken');

    router.push('/'); 
 }  

  return (
    <div className="flex h-screen">
      <div className="w-1/4 bg-gray-800 text-white p-5 mt-40 h-screen fixed">
        <h2 className="text-2xl font-semibold mb-6">Categories</h2>
        <ul className="list-none">
          <li className="mb-4 hover:bg-gray-600 p-2 rounded cursor-pointer">Templates</li>
          <li className="mb-4 hover:bg-gray-600 p-2 rounded cursor-pointer">
            <Link href="/blog-posts">Blog Posts</Link>
          </li>
          {isAdmin && (
            <li className="mb-4 hover:bg-gray-600 p-2 rounded cursor-pointer">
              <Link href="/admin-reports">Admin Reports</Link>
            </li>
          )}
        </ul>
      </div>
      <div className="flex-1 bg-gray-100 p-6">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-5xl font-bold text-gray-800">Scriptorium</h1>
          <div className="flex items-center space-x-4">

             {/* Generated by ChatGPT */}

            {avatar && (
              <div className="w-12 h-12 rounded-full overflow-hidden border-2 border-blue-500">
                <img src={avatar} alt="User Avatar" className="w-full h-full object-cover" />
              </div>
            )}
      
            <Link href='/edit-profile'>
              <button className="bg-green-500 text-white px-4 py-2 rounded hover:bg-blue-600">
                Edit Profile
              </button>
            </Link>
            <button
              className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
              onClick={handleLogout}
            >
              Log Out
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LoggedIn;