import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export default async function handler(req, res) {
    
    if (req.method === "GET") {
        const { sortingType } = req.query;

        let blogPosts;

        if (sortingType === 'valued') {

            blogPosts = await prisma.blogPost.findMany({
                orderBy: { // generated by ChatGPT
                    rating: 'desc',
                }
            });
        
        } else if (sortingType === 'controversial') {

            blogPosts = await prisma.blogPost.findMany({
                orderBy: { // generated by ChatGPT
                    rating: 'asc',
                }
            });

        } else {
            res.status(400).json({ message: "Sorting Type is not valid" });
        }

        return res.status(200).json(blogPosts);

    } else {
        res.status(405).json({ message: "Method not allowed" });
    }
}