import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export default async function handler(req, res) {

    // returns blog posts that mention a particular template (in either their title or their description)
    if (req.method == "GET") {

        const { name, page = 1, limit = 10 } = req.query;

        // generated by ChatGPT
        const templates = await prisma.template.findMany({
            where: {
                title: {
                    equals: name
                }
            }
        });

        if (templates.length == 0) {
            return res.status(400).json({ error: 'No templates have the given name' });
        }

        const skip = (page - 1) * limit; 
        const take = parseInt(limit);

        const blogPosts = await prisma.blogPost.findMany({
            where: {
                OR: [
                    {
                        title: {
                            contains: name
                        }
                    },
                    {
                        description: {
                            contains: name
                        }
                    }
                ]
            },
            include: { linkToTemplates: true },
            skip: skip,
            take: take,
        });

        return res.status(200).json({
            page: parseInt(page),       
            limit: take,                
            data: blogPosts,
        });

    }

}